[package]
name = "cmus-status-line"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
htmlescape = "0.3.1"
regex      = "1.3.1"
ron        = "0.5.1"
serde      = { version = "1.0.102", features = ["derive"] }
toml       = "0.5.5"
