format = """
%{ If(IsStatus(Playing),
    Text("Cmus is playing a song!")) }

%{MatchStatus(Playing, "")}
%{MatchStatus(Paused, "")}
%{MatchStatus(Stopped, "")} 
%{ If(IsStatus(Playing),
    MaxLen(Title, 60))
}  
%{ProgressBar("<####---->")}
"""

[output]
escape_html = false
