format = """
%{ If(
    And(And(
        Not(IsStatus(Paused)),
        Or(IsStatus(Playing), IsStatus(Stopped)),
    ), True),
    Container([
        Container([
            If(IsStatus(Playing),
                Text(" ")),
            If(IsStatus(Paused),
                Text(" ")),
            If(IsStatus(Stopped),
                Text(" ")),
        ]),
        Title,
        Text("  "),
        ProgressBar("<####---->"),
    ])
)}
"""

[output]
escape_html = false
