format = """
%{ If(
    Or( IsStatus(Playing), IsStatus(Paused) ),
    Container([
        Container([
            If(IsStatus(Playing),
                Text(" ")),
            If(IsStatus(Paused),
                Text(" ")),
            If(IsStatus(Stopped),
                Text(" ")),
        ]),
        Title,
        Text("  "),
        ProgressBar("<####---->"),
    ])
)}
"""

[output]
escape_html = false
